Fix workflow syntax

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -28,7 +28,7 @@ jobs:
   # Build job
   build:
     runs-on: ubuntu-latest
-    steps:
+    steps.
       - name: Checkout
         uses: actions/checkout@v4
       - name: Detect package manager
@@ -40,13 +40,14 @@ jobs:
             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
             exit 0
           else
-            echo "Unable to determine package manager" >> 1
+            echo "Unable to determine package manager"
+            exit 1
           fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node_version: "20"
-          cache: ${{ steps: detect-package-manager.outputs.manager }}
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
       - name: Setup Pages
         uses: actions/configure-pages@v5
         with:
@@ -64,9 +65,9 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
       - name: Install dependencies
-        run: ${{ steps: detect-package-manager.outputs.manager }} ${{ steps: detect-package-manager.outputs.command }}
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
       - name: Build with Next.js
-        run: ${{ steps: detect-package-manager.outputs.runner }} next build
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
@@ -76,10 +77,10 @@ jobs:
   deploy:
     environment:
       name: github-pages
-      url: ${{ steps: deployment.outputs.page_url }}
+      url: ${{ steps. deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     needs: build
-    steps:
+    steps.
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
